### ISSUE TITLE
Is Jekyll necessary?

### ISSUE THREAD

**Issue by fortruce** [socialtables/code-of-conduct#1]
Does this benefit enough from Jekyll to warrant the added complexity? It creates a barrier to entry for people to modify vs a simple .md or .html file (and there is currently no way to even see our version of it).

**Comment by johnelliott** [comment]
Agreed, just a .md would be great.

**Comment by necaris** [comment]
I don't know about Jekyll, but I'm +1 on publishing this a little more widely than just an internal `.md` -- whether that's Jekyll, Ghost, Metalsmith, Gatsby...

**Comment by danmactough** [comment]
Jekyll is certainly not necessary, but this is a fork of repo that used it. To me, it does not seem worthwhile to rewrite it. Once we agree on the content, this will be published, and GitHub pages makes that really simple. So simple, that it actually **_is**_ published: http://socialtables.github.io/code-of-conduct/
